/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DeVivo_JrInterface */

#ifndef _Included_DeVivo_JrInterface
#define _Included_DeVivo_JrInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DeVivo_JrInterface
 * Method:    JrConnect
 * Signature: (ILjava/lang/String;[I)I
 */
JNIEXPORT jint JNICALL Java_DeVivo_JrInterface_JrConnect
  (JNIEnv *, jobject, jint, jstring, jlongArray);

/*
 * Class:     DeVivo_JrInterface
 * Method:    JrDisconnect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_DeVivo_JrInterface_JrDisconnect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     DeVivo_JrInterface
 * Method:    JrSend
 * Signature: (III[B)I
 */
JNIEXPORT jint JNICALL Java_DeVivo_JrInterface_JrSend
  (JNIEnv *, jobject, jlong, jint, jint, jbyteArray);

/*
 * Class:     DeVivo_JrInterface
 * Method:    JrReceive
 * Signature: (I[I[I[B)I
 */
JNIEXPORT jint JNICALL Java_DeVivo_JrInterface_JrReceive
  (JNIEnv *, jobject, jlong, jintArray, jintArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
