#***********           LICENSE HEADER   *******************************
# JR Middleware
# Copyright (c)  2008-2019, DeVivo AST, Inc
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without 
# modification, are permitted provided that the following conditions are met:
# 
#        Redistributions of source code must retain the above copyright notice, 
# this list of conditions and the following disclaimer.
# 
#        Redistributions in binary form must reproduce the above copyright 
# notice, this list of conditions and the following disclaimer in the 
# documentation and/or other materials provided with the distribution.
# 
#        Neither the name of the copyright holder nor the names of 
# its contributors may be used to endorse or promote products derived from 
# this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" 
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE 
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE 
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE 
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR 
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF 
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS 
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN 
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) 
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE 
# POSSIBILITY OF SUCH DAMAGE.
# *********************  END OF LICENSE ***********************************
 
# Import base environment
import os
Import( 'baseEnv' )

# Define multiple environments for using the library
# as either static or shared
dllenv = baseEnv.Clone()
dllenv.Append( CCFLAGS = ['-D__USE_DLL__'] ) 

# On Windows, use a DLL for the API.
if os.name == "nt":
                                                                
    testapp = dllenv.Program( target = 'jr_test',
							 source = 'jr_test.cpp',
							 LIBS = 'Junior' )
							 
    jrcharapp = dllenv.Program( target = 'jr_char',
							     source = 'jr-char1.cpp',
							     LIBS = 'Junior' )							 
							 

else:
                           
    testapp = baseEnv.Program( target = 'jr_test',
							  source = 'jr_test.cpp',
							  LIBS = 'Junior' )
						  
    jrcharapp = baseEnv.Program( target = 'jr_char',
							  source = 'jr-char1.cpp',
							  LIBS = 'Junior' )
						  

	                                                    
baseEnv.Install( baseEnv['INSTALL_BINDIR'], testapp )
baseEnv.Install( baseEnv['INSTALL_BINDIR'], jrcharapp )
