import os
Import( 'baseEnv' )

API_Files = [
    'JuniorAPI.cpp',
    'JrSockets.cpp',
    'JuniorMgr.cpp',
    'OS.cpp',
    'ConfigData.cpp'
]


OCUFiles = [
    'OCU.cpp'
]

RTE_Files =[
    'JuniorRTE.cpp',
    'JUDPTransport.cpp'
]
if os.name == "nt":  
	libs =['WSock32.lib', 'Junior.lib']
else:
	libs = ['libJunior.a']
	

# Generate both the OCU and Robot test programs
apilib = baseEnv.Library(  target = 'Junior',
                           source = API_Files )

ocuapp = baseEnv.Program( target = 'ocu',
                          source = OCUFiles,
                          LIBS = libs )
rteapp = baseEnv.Program( target = 'JuniorRTE',
                          source = RTE_Files,
                          LIBS = libs )
                           

baseEnv.Install( baseEnv['INSTALL_LIBDIR'], apilib )
baseEnv.Install( baseEnv['INSTALL_BINDIR'], ocuapp )
baseEnv.Install( baseEnv['INSTALL_BINDIR'], rteapp )
baseEnv.Install( baseEnv['INSTALL_BINDIR'], 'junior.cfg' )